export type SetupDraft = {
  weight: string;
  goalWeight: string;
  bodyFat: string;
  goalBodyFat: string;
  gender: string;
  birthDate: string;
  timezone: string;
  wantsCoach: boolean;
  hasExistingWeight: boolean;
  heightFeet: string;
  heightInches: string;
  foodAllergies: string;
  dietaryPreferences: string;
  activityLevel: string;
  phone: string;
  occupation: string;
  assignedCoachName: string;
  hasAssignedCoach: boolean;
};

export type SetupFormState = {
  weight: string;
  goalWeight: string;
  bodyFat: string;
  goalBodyFat: string;
  heightFeet: string;
  heightInches: string;
  occupation: string;
  activityLevel: string;
  coachCode: string;
  wantsCoach: boolean;
  selectedVirtualCoachId: string;
  trackingOnly: boolean;
  gender: '' | 'm' | 'f';
  birthDate: string;
  timezone: string;
  phone: string;
  foodAllergies: string;
  dietaryPreferences: string;
  textReminders: '' | 'yes' | 'no';
};
